# Generated by Django 4.2.4 on 2025-02-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('auth_date', models.DateField()),
                ('auth_time', models.TimeField()),
                ('direction', models.CharField(max_length=10)),
                ('device_name', models.CharField(max_length=100)),
                ('device_serial_no', models.CharField(max_length=100)),
                ('person_name', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
