# Generated by Django 4.2.4 on 2025-02-08 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_attendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'managed': False},
        ),
    ]
