# Generated by Django 4.2.4 on 2025-02-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_teachers_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='hour',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
