# Generated by Django 4.2.4 on 2025-02-15 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_lesson_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='application.teachers'),
        ),
    ]
