# Generated by Django 4.1.2 on 2025-07-04 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_alter_lesson_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='user',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Proposal',
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
    ]
