# Generated by Django 4.1.2 on 2025-07-12 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0009_remove_lesson_teacher_remove_proposal_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('lastname', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('middle_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('position', models.CharField(blank=True, choices=[('admin', 'Админ'), ('HR', 'Отдел кадров'), ('zavuch', 'Завуч')], max_length=20, null=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
