# Generated by Django 4.1.2 on 2025-07-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
