# Generated by Django 4.1.2 on 2025-07-13 13:55

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_profile_approve'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('lastname', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('middle_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('position', models.CharField(blank=True, choices=[('teacher', 'Учитель'), ('other', 'Другое')], max_length=20, null=True)),
                ('position_gender', models.CharField(blank=True, choices=[('male', 'Муж'), ('female', 'Жен')], max_length=20, null=True)),
                ('date_birth', models.DateField(blank=True, default=None, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/')),
                ('cv_rus', models.FileField(blank=True, null=True, upload_to='staff/')),
                ('cv_uz', models.FileField(blank=True, null=True, upload_to='staff/')),
                ('diplom', models.FileField(blank=True, null=True, upload_to='staff/')),
                ('adres', models.CharField(max_length=200)),
                ('passport', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
