# Generated by Django 4.1.2 on 2025-07-13 18:08

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('lastname', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('middle_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('date_birth', models.DateField(blank=True, default=None, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/')),
                ('adres', models.CharField(max_length=200)),
                ('passport', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('prikaz', models.IntegerField(default=None)),
                ('prikaz_date', models.DateField(blank=True, null=True)),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.schoolclass')),
            ],
        ),
    ]
