# Generated by Django 4.1.2 on 2025-07-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_schoolclass_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='position_gender',
            field=models.CharField(blank=True, choices=[('male', 'Муж'), ('female', 'Жен')], max_length=20, null=True),
        ),
    ]
