# Generated by Django 4.1.2 on 2025-07-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_student_position_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='prikaz_archive',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='prikaz_date_archive',
            field=models.DateField(blank=True, null=True),
        ),
    ]
