# Generated by Django 4.2.4 on 2025-08-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_alter_student_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=0)),
                ('categories', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
