# Generated by Django 4.2.4 on 2025-08-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='price',
        ),
        migrations.AddField(
            model_name='invoice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
