# Generated by Django 4.2.4 on 2025-09-05 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_remove_warehouse_price_invoice_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, choices=[('admin', 'Админ'), ('HR', 'Отдел кадров'), ('supplier', 'Завхоз'), ('zavuch', 'Завуч')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_payment', models.CharField(choices=[('cash', 'Наличные'), ('bank', 'Банковские переводы'), ('card', 'Карта')], max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.schoolclass')),
            ],
        ),
    ]
