# Generated by Django 4.2.4 on 2025-09-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_alter_payment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
