# Generated by Django 4.2.4 on 2025-09-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_payment_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
