# Generated by Django 4.2.4 on 2025-09-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_payment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_type',
            field=models.CharField(choices=[('debt', 'Начисление'), ('payment', 'Оплата')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type_of_payment',
            field=models.CharField(blank=True, choices=[('cash', 'Наличные'), ('bank', 'Банковские переводы'), ('card', 'Карта')], max_length=20, null=True),
        ),
    ]
