# Generated by Django 4.2.4 on 2025-10-03 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0026_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='application.student'),
        ),
    ]
