# Generated by Django 4.2.4 on 2025-10-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0028_alter_discount_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
