# Generated by Django 4.2.4 on 2025-11-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0031_alter_student_school_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='unit',
            field=models.CharField(choices=[('шт', 'Штука'), ('кг', 'Килограмм'), ('г', 'Грамм'), ('л', 'Литр'), ('мл', 'Миллитр')], default='шт', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
