# Generated by Django 4.2.4 on 2025-11-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0032_invoice_unit_alter_invoice_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='unit',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='unit',
            field=models.CharField(choices=[('шт', 'Штука'), ('кг', 'Килограмм'), ('г', 'Грамм'), ('л', 'Литр'), ('мл', 'Миллитр')], default='шт', max_length=10),
        ),
    ]
