# Generated by Django 4.2.4 on 2025-11-17 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0034_alter_invoice_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='application.warehouse'),
        ),
    ]
