# Generated by Django 4.2.4 on 2025-11-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0035_alter_invoice_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='type_of_payment',
            field=models.CharField(blank=True, choices=[('cash', 'Наличные'), ('bank', 'Банковские переводы'), ('card', 'Карта')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, choices=[('admin', 'Админ'), ('HR', 'Отдел кадров'), ('supplier', 'Завхоз'), ('chief', 'Повар'), ('zavuch', 'Завуч')], max_length=20, null=True),
        ),
    ]
