# Generated by Django 4.2.4 on 2026-04-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0036_invoice_type_of_payment_payment_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='remaining_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
