# Generated by Django 4.2.4 on 2026-04-06 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0037_invoice_remaining_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='application.warehouse'),
        ),
    ]
