# Generated by Django 4.2.4 on 2026-04-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0038_alter_invoice_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='education_type',
            field=models.CharField(choices=[('school', 'Школа'), ('kindergarten', 'Садик'), ('preschool', 'Подготовка')], default='school', max_length=20),
        ),
    ]
