# Generated by Django 4.2.4 on 2026-04-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0039_student_education_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
    ]
