# Generated by Django 4.2.4 on 2026-04-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0041_inventory_cabinet_inventory_items_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
