# Generated by Django 4.2.4 on 2026-04-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0042_inventory_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_cabinet',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='inventory_items',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
