# Generated by Django 4.2.4 on 2026-04-30 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0043_alter_inventory_cabinet_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory_cabinet',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_inventory', to='application.schoolclass'),
        ),
    ]
