# Generated by Django 4.2.4 on 2026-04-30 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0044_inventory_cabinet_school_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_student', to='application.student'),
        ),
    ]
