# Generated by Django 4.2.4 on 2026-05-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0045_alter_payment_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type_of_payment',
            field=models.CharField(blank=True, choices=[('cash', 'Наличные'), ('bank', 'Карта'), ('card', 'Банковские переводы')], max_length=20, null=True),
        ),
    ]
