# Generated by Django 4.2.4 on 2026-05-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0046_alter_payment_type_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateField(null=True),
        ),
    ]
