# Generated by Django 4.2.4 on 2026-05-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0047_alter_payment_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turniket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='')),
                ('role', models.CharField(choices=[('worker', 'Сотрудник'), ('student', 'Ученик')], max_length=50)),
            ],
        ),
    ]
