# Generated by Django 4.2.4 on 2026-05-18 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0048_turniket'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingTurniket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('enter', models.CharField(choices=[('in', 'Вход'), ('out', 'Выход')], max_length=20)),
                ('turniket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_student', to='application.turniket')),
            ],
        ),
    ]
