# Generated by Django 4.1.2 on 2026-05-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0049_trackingturniket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turniket',
            name='photo',
            field=models.ImageField(upload_to='face/'),
        ),
    ]
