# Generated by Django 4.1.2 on 2026-05-29 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0050_alter_turniket_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('active_this_season', models.BooleanField(default=True)),
                ('base_student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camp_profile', to='application.student')),
                ('camp_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.schoolclass')),
            ],
        ),
    ]
