# Generated by Django 4.1.2 on 2026-05-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0051_campstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='campstudent',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='campstudent',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
    ]
