# Generated by Django 4.1.2 on 2026-05-29 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0052_campstudent_created_at_campstudent_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('transaction_type', models.CharField(choices=[('debt', 'Начисление'), ('payment', 'Оплата')], max_length=10, null=True)),
                ('type_of_payment', models.CharField(blank=True, choices=[('cash', 'Наличные'), ('bank', 'Карта'), ('card', 'Банковские переводы')], max_length=20, null=True)),
                ('sum', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('created_at', models.DateField(null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_student', to='application.campstudent')),
            ],
        ),
    ]
